# fly.toml app configuration file generated for assay-plate-server on 2024-02-02T03:07:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'assay-plate-server'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[env]
  FRONTEND_URL = "https://assayplate.onrender.com"
  NODE_ENV = "production"
  PORT = "3000"